services:
  maplesauna:
    # network_mode: "host"
    build: .
    container_name: maplesauna
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: 0.0.0.0
      DB_URL: jdbc:mysql://db:3306/maplesauna?characterEncoding=latin1
      # WAIT_HOSTS: localhost:3306
    ports:
      - "8484:8484"
      - "7575:7575"
      - "7576:7576"
      - "7577:7577"
    restart: unless-stopped
    
  db:
    # network_mode: "host"
    image: mysql:5.6
    container_name: maplesauna-db
    environment:
      MYSQL_DATABASE: maplesauna
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: 
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppassword"]
      interval: 10s
      retries: 5
